### ISSUE TITLE
charts: configure RBAC for minikube

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renga#167]
- [ ] configure RBAC (`kubectl apply -f minikube-rbac.yml`)

**`minikube-rbac.yml`**
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: service-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default  # or renga depending on your deployment
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
